export type ComponentExample = {
  slug: string;
  name: string;
  description?: string;
  /** Optional install slug for variants that have their own registry command. */
  installSlug?: string;
  /** Source file shown under Source tab. */
  file: string;
  /** Key into the previews registry (e.g. "motion/button-base"). */
  previewKey: string;
  /** Path to the preview file used for the Usage tab. */
  previewFile: string;
};

export type ComponentEntry = {
  slug: string;
  name: string;
  /** Breadcrumb group shown between category and component name, e.g. "Avatar". */
  group?: string;
  description: string;
  file: string;
  badge?: "new";
  /** ISO date the component shipped. Drives newest-first order in the landing
   * "Recently launched" section. Set it when adding a "new" badge component. */
  launchedAt?: string;
  /** Optional hand-tuned SEO keywords, merged on top of generated ones. */
  keywords?: string[];
  /** Extra source files bundled under this slug (e.g. multi-file components). */
  extraFiles?: string[];
  /** Per-variant breakdown rendered as separate Preview / Usage / Source on the page. */
  examples?: ComponentExample[];
  /** Filter tags shown as chips on the category page (e.g. "form", "overlay", "mobile").
   *  Must only use tags from the canonical set defined in component-filter.tsx. */
  tags?: string[];
};

export type CategoryEntry = {
  slug: string;
  name: string;
  description: string;
  components: ComponentEntry[];
};

export const registry: CategoryEntry[] = [
  {
    slug: "motion",
    name: "Components",
    description: "Bespoke motion primitives with shadcn-compatible registry endpoints.",
    components: [
      {
        slug: "tilt-card",
        name: "Tilt Card",
        group: "Card",
        description: "3D perspective tilt on hover with cursor-tracked glare.",
        file: "components/motion/tilt-card.tsx",
        tags: ["interaction", "hover", "card"],
      },
      {
        slug: "stat-card",
        name: "Stat Card",
        group: "Data",
        description: "Plain KPI card with a label, value and an up/down trend chip. No motion.",
        file: "components/static/stat-card.tsx",
        badge: "new",
        launchedAt: "2026-07-14",
        tags: ["data", "display"],
      },
      {
        slug: "testimonial-card",
        name: "Testimonial Card",
        group: "Marketing",
        description: "Plain quote card with star rating, avatar and byline. No motion.",
        file: "components/static/testimonial-card.tsx",
        badge: "new",
        launchedAt: "2026-07-14",
        tags: ["marketing", "display", "social"],
      },
      {
        slug: "button",
        name: "Button",
        group: "Button",
        description: "Spring-pressed Button plus StatefulButton (idle → loading → success / error) and MagneticButton.",
        file: "components/motion/button/index.tsx",
        extraFiles: [
          "components/motion/button/base.tsx",
          "components/motion/button/stateful.tsx",
          "components/motion/button/magnetic.tsx",
        ],
        tags: ["interaction", "form", "input"],
        examples: [
          {
            slug: "base",
            name: "Button",
            description: "Press scale, hover lift, variants and sizes.",
            installSlug: "button-base",
            file: "components/motion/button/base.tsx",
            previewKey: "motion/button-base",
            previewFile: "components/previews/motion/button-base.preview.tsx",
          },
          {
            slug: "stateful",
            name: "Stateful Button",
            description: "Idle → loading → success / error with blur-swap slots and morphing width.",
            installSlug: "button-stateful",
            file: "components/motion/button/stateful.tsx",
            previewKey: "motion/button-stateful",
            previewFile: "components/previews/motion/button-stateful.preview.tsx",
          },
          {
            slug: "magnetic",
            name: "Magnetic Button",
            description: "Spring-attracted to the cursor and repels on leave.",
            installSlug: "button-magnetic",
            file: "components/motion/button/magnetic.tsx",
            previewKey: "motion/button-magnetic",
            previewFile: "components/previews/motion/button-magnetic.preview.tsx",
          },
        ],
      },
      {
        slug: "marquee",
        name: "Marquee",
        group: "Animation",
        description: "Continuous horizontal or vertical scroll loop, pause-on-hover, and reversed direction.",
        file: "components/motion/marquee.tsx",
        tags: ["display", "scroll", "media"],
      },
      {
        slug: "tabs",
        name: "Tabs",
        group: "Navigation",
        description: "Tab set with a shared-layout animated underline that glides between active tabs.",
        file: "components/motion/tabs.tsx",
        tags: ["navigation", "layout"],
      },
      {
        slug: "switch",
        name: "Switch",
        group: "Form",
        description: "Sliding toggle with spring thumb physics and reduced-motion fallback.",
        file: "components/motion/switch.tsx",
        tags: ["form", "toggle", "input"],
      },
      {
        slug: "input",
        name: "Input",
        group: "Form",
        description: "Text input with animated floating label, error shake, success/error state icons, and hint text.",
        file: "components/motion/input.tsx",
        tags: ["form", "text", "input"],
      },
      {
        slug: "select",
        name: "Select",
        group: "Form",
        description: "Animated select primitives for native-feeling dropdowns with spring motion.",
        file: "components/motion/select.tsx",
        tags: ["form", "dropdown", "input"],
        examples: [
          {
            slug: "default",
            name: "Select",
            description: "Click-triggered dropdown with spring enter/exit and animated active row.",
            installSlug: "select",
            file: "components/motion/select.tsx",
            previewKey: "motion/select",
            previewFile: "components/previews/motion/select.preview.tsx",
          },
          {
            slug: "morph",
            name: "Morph Select",
            description: "Select that morphs open from the trigger corner via a clip-path spring.",
            installSlug: "select-morph",
            file: "components/motion/select-morph.tsx",
            previewKey: "motion/select-morph",
            previewFile: "components/previews/motion/select-morph.preview.tsx",
          },
        ],
      },
      {
        slug: "checkbox",
        name: "Checkbox",
        group: "Form",
        description: "Checkbox with a spring-drawn check mark and reduced-motion fallback.",
        file: "components/motion/checkbox.tsx",
        tags: ["form", "input"],
      },
      {
        slug: "radio",
        name: "Radio Group",
        group: "Form",
        description: "Radio group with a shared-layout animated selection ring.",
        file: "components/motion/radio.tsx",
        tags: ["form", "input"],
      },
      {
        slug: "bottom-sheet",
        name: "Bottom Sheet",
        group: "Overlay",
        description: "Vaul-inspired draggable bottom sheet with snap points, inertia and glass surface.",
        file: "components/motion/bottom-sheet.tsx",
        tags: ["overlay", "mobile", "drag"],
      },
      {
        slug: "shared-layout-bg",
        name: "Shared Layout Background",
        group: "Layout",
        description: "A pill that glides between hovered items via motion's shared layout, with blur enter/exit.",
        file: "components/motion/shared-layout-bg.tsx",
        tags: ["interaction", "hover", "layout"],
      },
      {
        slug: "dock",
        name: "Dock",
        group: "Navigation",
        description: "macOS-style dock with grouped actions and a gliding active pill.",
        file: "components/motion/dock.tsx",
        tags: ["navigation", "layout"],
      },
      {
        slug: "tooltip",
        name: "Tooltip",
        group: "Overlay",
        description: "Hover or focus tooltip with blur enter/exit and spring spawn.",
        file: "components/motion/tooltip.tsx",
        tags: ["overlay", "feedback"],
      },
      {
        slug: "morphing-modal",
        name: "Morphing Modal",
        group: "Overlay",
        description: "Family-app-style modal. A single panel that morphs its height as you navigate between inner views, with blur cross-fade on content.",
        file: "components/motion/morphing-modal.tsx",
        tags: ["overlay", "navigation"],
      },
      {
        slug: "text-animation",
        name: "Text Animation",
        group: "Text",
        description: "Animated text primitives for reveal sequences, shimmer loading states and letter-cascade swaps.",
        file: "components/motion/text-reveal.tsx",
        extraFiles: [
          "components/motion/text-shimmer.tsx",
          "components/motion/text-cascade.tsx",
        ],
        tags: ["display", "text"],
        examples: [
          {
            slug: "reveal",
            name: "Text Reveal",
            description: "Word or character reveal with spring slide-up and blur.",
            installSlug: "text-reveal",
            file: "components/motion/text-reveal.tsx",
            previewKey: "motion/text-reveal",
            previewFile: "components/previews/motion/text-reveal.preview.tsx",
          },
          {
            slug: "shimmer",
            name: "Text Shimmer",
            description: "Gradient sweep across text for loading or emphasis.",
            installSlug: "text-shimmer",
            file: "components/motion/text-shimmer.tsx",
            previewKey: "motion/text-shimmer",
            previewFile: "components/previews/motion/text-shimmer.preview.tsx",
          },
          {
            slug: "cascade",
            name: "Text Cascade",
            description: "Letter-by-letter slot roll for standalone text — old letters drop away as new ones land, left to right.",
            installSlug: "text-cascade",
            file: "components/motion/text-cascade.tsx",
            previewKey: "motion/text-cascade",
            previewFile: "components/previews/motion/text-cascade.preview.tsx",
          },
        ],
      },
      {
        slug: "number",
        name: "Number Animation",
        group: "Counter",
        description: "Animated number primitives for count-up values and rolling digit tickers.",
        file: "components/motion/animated-number.tsx",
        extraFiles: ["components/motion/number-ticker.tsx"],
        tags: ["display", "counter", "data"],
        examples: [
          {
            slug: "ticker",
            name: "Number Ticker",
            description: "Slot-machine rolling digits with staggered entry.",
            installSlug: "number-ticker",
            file: "components/motion/number-ticker.tsx",
            previewKey: "motion/number-ticker",
            previewFile: "components/previews/motion/number-ticker.preview.tsx",
          },
          {
            slug: "animated",
            name: "Animated Number",
            description: "Spring-driven count-up triggered when in view.",
            installSlug: "animated-number",
            file: "components/motion/animated-number.tsx",
            previewKey: "motion/animated-number",
            previewFile: "components/previews/motion/animated-number.preview.tsx",
          },
        ],
      },
      {
        slug: "animated-badge",
        name: "Animated Badge",
        group: "Badge",
        description: "Status badge with animated state icons, pulse feedback and compact size variants.",
        file: "components/motion/animated-badge.tsx",
        tags: ["display", "feedback", "status"],
      },
      {
        slug: "action-swap",
        name: "Action Swap",
        group: "Button",
        description: "CTA button and slot primitives for swapping text and icons with blur motion.",
        file: "components/motion/action-swap.tsx",
        tags: ["interaction", "display", "text"],
        examples: [
          {
            slug: "cascade",
            name: "Cascade",
            description: "Letter-by-letter slot roll — the old label's letters drop away as the new ones land, left to right.",
            installSlug: "action-swap-cascade",
            file: "components/motion/action-swap-cascade.tsx",
            previewKey: "motion/action-swap-cascade",
            previewFile: "components/previews/motion/action-swap-cascade.preview.tsx",
          },
          {
            slug: "blur",
            name: "Blur",
            description: "Copy-button style swap with blur, opacity and scale.",
            installSlug: "action-swap-blur",
            file: "components/motion/action-swap-blur.tsx",
            previewKey: "motion/action-swap-blur",
            previewFile: "components/previews/motion/action-swap-blur.preview.tsx",
          },
          {
            slug: "roll",
            name: "Roll",
            description: "The next text or icon rolls in from below with blur.",
            installSlug: "action-swap-roll",
            file: "components/motion/action-swap-roll.tsx",
            previewKey: "motion/action-swap-roll",
            previewFile: "components/previews/motion/action-swap-roll.preview.tsx",
          },
        ],
      },
      {
        slug: "animated-toast-stack",
        name: "Animated Toast Stack",
        group: "Notification",
        description: "Stacked toasts with status morphs, swipe dismissal, actions and layout-aware motion.",
        file: "components/motion/animated-toast-stack.tsx",
        tags: ["overlay", "feedback", "notification"],
      },
      {
        slug: "theme-toggle",
        name: "Theme Toggle",
        group: "Toggle",
        description: "Theme toggle button with a full-page rectangle clip-path reveal via the View Transition API.",
        file: "components/motion/theme-toggle.tsx",
        tags: ["interaction", "display", "toggle"],
      },
      {
        slug: "bouncy-accordion",
        name: "Bouncy Accordion",
        group: "Disclosure",
        description: "Single-open accordion with weighted spring layout, icon rows and reduced-motion-safe content reveals.",
        file: "components/motion/bouncy-accordion.tsx",
        tags: ["navigation", "layout", "disclosure"],
      },
      {
        slug: "drawer",
        name: "Drawer",
        group: "Overlay",
        description: "Side panel that slides in from the left or right with a spring, backdrop blur, body scroll lock and esc-to-close.",
        file: "components/motion/drawer.tsx",
        tags: ["overlay", "navigation", "mobile"],
      },
      {
        slug: "scroll-animation",
        name: "Scroll Animation",
        group: "Scroll",
        description: "Scroll-driven motion: a Lenis smooth-scroll provider and a reading-progress indicator that reads from it.",
        file: "components/motion/smooth-scroll.tsx",
        extraFiles: [
          "components/motion/scroll-progress.tsx",
          "components/motion/parallax.tsx",
          "components/motion/scroll-to.tsx",
          "components/motion/scroll-reveal.tsx",
        ],
        tags: ["scroll", "layout"],
        keywords: [
          "smooth scroll",
          "lenis",
          "scroll progress",
          "reading progress",
          "momentum scroll",
          "scroll velocity",
        ],
        examples: [
          {
            slug: "smooth-scroll",
            name: "Smooth Scroll",
            description: "Smooth-scroll provider over Lenis with a useSmoothScroll hook exposing scroll offset, progress and velocity. Reduced-motion safe.",
            installSlug: "smooth-scroll",
            file: "components/motion/smooth-scroll.tsx",
            previewKey: "motion/smooth-scroll",
            previewFile: "components/previews/motion/smooth-scroll.preview.tsx",
          },
          {
            slug: "scroll-progress",
            name: "Scroll Progress",
            description: "Reading-progress indicator — fixed bar or circular ring — driven by scroll position via useSmoothScroll, with spring smoothing.",
            installSlug: "scroll-progress",
            file: "components/motion/scroll-progress.tsx",
            previewKey: "motion/scroll-progress",
            previewFile: "components/previews/motion/scroll-progress.preview.tsx",
          },
          {
            slug: "parallax",
            name: "Parallax",
            description: "Wrapper that drifts its children at a speed factor as they cross the viewport, on either axis. Reduced-motion safe.",
            installSlug: "parallax",
            file: "components/motion/parallax.tsx",
            previewKey: "motion/parallax",
            previewFile: "components/previews/motion/parallax.preview.tsx",
          },
          {
            slug: "scroll-to",
            name: "Scroll To",
            description: "Button that smooth-scrolls to a target (offset, selector or element) via the active SmoothScroll provider; reduced-motion jumps instantly.",
            installSlug: "scroll-to",
            file: "components/motion/scroll-to.tsx",
            previewKey: "motion/scroll-to",
            previewFile: "components/previews/motion/scroll-to.preview.tsx",
          },
          {
            slug: "scroll-reveal",
            name: "Scroll Reveal",
            description: "Reveals its children with a spring slide and blur as they enter the viewport, once or every time. Reduced-motion keeps a fade.",
            installSlug: "scroll-reveal",
            file: "components/motion/scroll-reveal.tsx",
            previewKey: "motion/scroll-reveal",
            previewFile: "components/previews/motion/scroll-reveal.preview.tsx",
          },
        ],
      },
      {
        slug: "range-slider",
        name: "Range Slider",
        group: "Form",
        description: "Range slider with tick dots and a bouncy vertical-bar thumb that glides between snapped steps; drag and keyboard control, reduced-motion safe.",
        file: "components/motion/range-slider.tsx",
        tags: ["form", "input", "drag"],
        keywords: ["slider", "range slider", "range input", "stepped slider", "ticks"],
      },
      {
        slug: "table",
        name: "Table",
        group: "Data",
        description:
          "Virtualized data table that stays smooth at 10k+ rows, with sortable headers, row selection, column resize and reorder, and a sticky header. Minimal, reduced-motion-safe motion.",
        file: "components/motion/table/index.tsx",
        tags: ["data", "display", "layout"],
        keywords: [
          "react data table",
          "virtualized table",
          "sortable table",
          "table row selection",
          "react table 10k rows",
          "editable table react",
        ],
        examples: [
          {
            slug: "data",
            name: "Data Table",
            description:
              "10k virtualized rows with sortable headers, row selection, column resize and reorder.",
            installSlug: "table",
            file: "components/motion/table/index.tsx",
            previewKey: "motion/table",
            previewFile: "components/previews/motion/table.preview.tsx",
          },
          {
            slug: "editable",
            name: "Editable Table",
            description:
              "Edit cells inline and insert or delete rows and columns via border handles; the table re-renders from the updated data and column defs.",
            installSlug: "table-editable",
            file: "components/motion/table/index.tsx",
            previewKey: "motion/table-editable",
            previewFile: "components/previews/motion/table-editable.preview.tsx",
          },
          {
            slug: "async",
            name: "Async Table",
            description:
              "Loads pages on demand — skeleton rows on first load, then infinite scroll via onEndReached as the virtualized list nears the bottom.",
            installSlug: "table-async",
            file: "components/motion/table/index.tsx",
            previewKey: "motion/table-async",
            previewFile: "components/previews/motion/table-async.preview.tsx",
          },
        ],
      },
      {
        slug: "shader-background",
        name: "Shader Background",
        group: "Background",
        description:
          "Canvas shader backgrounds (mesh gradient, grain, warp, waves, voronoi, dot orbit and more) with a single typed variant prop. Reduced-motion freezes animated variants.",
        file: "components/motion/shader-background.tsx",
        tags: ["display", "media", "visual", "background"],
        keywords: [
          "shader background react",
          "webgl background",
          "mesh gradient react",
          "animated background react",
          "canvas shader",
          "gradient background component",
        ],
      },
      {
        slug: "cylinder-carousel",
        name: "Cylinder Carousel",
        group: "Carousel",
        description:
          "A carousel whose items line the inside of a cylinder, receding into the center and growing toward the edges. Drag, scroll or arrow-key to roll it, with a springy glide and snap. Reduced-motion drops the glide.",
        file: "components/motion/cylinder-carousel.tsx",
        tags: ["display", "drag", "media"],
        keywords: [
          "3d carousel react",
          "cylinder carousel",
          "coverflow react",
          "rolling carousel",
          "draggable carousel react",
        ],
      },
      {
        slug: "loader",
        name: "Loader",
        group: "Status",
        description:
          "Loading indicator with seventeen variants: spinner, dots, bars, dot-matrix, dither, morph, comet, scramble, metaballs, newton, helix, percent, and five terminal-style ascii spinners. Scales from one size prop, uses currentColor, and reduced-motion swaps every transform for a calm opacity pulse.",
        file: "components/motion/loader.tsx",
        tags: ["feedback", "display", "status"],
        keywords: [
          "loader react",
          "loading spinner",
          "dot matrix loader",
          "dithering loader",
          "loading indicator",
        ],
      },
      {
        slug: "dialog",
        name: "Dialog",
        group: "Overlay",
        description:
          "Spring-scale modal with backdrop blur, focus trap, Esc-to-close, and body scroll lock. Composable sub-components: Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter, DialogClose.",
        file: "components/motion/dialog.tsx",
        tags: ["overlay", "interaction"],
        keywords: [
          "react dialog",
          "animated modal react",
          "spring modal",
          "accessible dialog react",
          "framer motion modal",
        ],
      },
      {
        slug: "dropdown-menu",
        name: "Dropdown Menu",
        group: "Navigation",
        description:
          "Click-triggered positioned menu with staggered item entrance, separator, label, shortcut and destructive variants. Closes on outside click, item select, or Esc.",
        file: "components/motion/dropdown-menu.tsx",
        tags: ["navigation", "overlay", "interaction"],
        keywords: [
          "react dropdown menu",
          "animated dropdown",
          "context menu react",
          "action menu react",
          "framer motion dropdown",
        ],
      },
      {
        slug: "popover",
        name: "Popover",
        group: "Overlay",
        description:
          "Click-triggered floating panel with side and alignment control, spring blur entrance, and outside-click / Esc dismissal. Composable sub-components: Popover, PopoverTrigger, PopoverContent, PopoverClose.",
        file: "components/motion/popover.tsx",
        tags: ["overlay", "interaction"],
        keywords: [
          "react popover",
          "animated popover",
          "floating panel react",
          "popover animation",
          "framer motion popover",
        ],
      },
      {
        slug: "popover-morph",
        name: "Morph Popover",
        group: "Overlay",
        badge: "new",
        launchedAt: "2026-07-11",
        description:
          "A popover panel that morphs open from the nearest trigger corner via a clip-path spring — no separate entrance animation, just the shape unclipping. Supports a glass backdrop-blur variant, optional caret arrow, and controlled or uncontrolled state.",
        file: "components/motion/popover-morph.tsx",
        tags: ["overlay", "interaction"],
        keywords: [
          "morph popover react",
          "clip path animation react",
          "corner morph panel",
          "animated popover react",
          "framer motion popover morph",
        ],
      },
      {
        slug: "preview-rail",
        name: "Preview Rail",
        group: "Navigation",
        badge: "new",
        launchedAt: "2026-07-11",
        description:
          "Vertical or horizontal navigation rail where items are lines that magnify on hover. Hovering a line reveals a preview panel with a blur fade transition. Controlled or uncontrolled with a custom renderPreview slot.",
        file: "components/motion/preview-rail.tsx",
        tags: ["navigation", "interaction", "layout"],
        keywords: [
          "navigation rail react",
          "line navigation react",
          "preview navigation react",
          "sidebar navigation react",
          "framer motion navigation",
        ],
      },
      {
        slug: "rainbow-cta",
        name: "Rainbow CTA",
        group: "Marketing",
        badge: "new",
        launchedAt: "2026-07-11",
        description:
          "A link or button wrapped in an infinitely animating rainbow gradient border. Supports rounded and pill shapes, any children, and respects prefers-reduced-motion by pausing the animation.",
        file: "components/motion/rainbow-cta.tsx",
        tags: ["interaction", "display", "marketing"],
        keywords: [
          "rainbow button react",
          "gradient border button",
          "animated cta react",
          "gradient cta react",
          "rainbow gradient react",
        ],
      },
      {
        slug: "page-nav",
        name: "Page Nav",
        group: "Navigation",
        badge: "new",
        launchedAt: "2026-07-11",
        description:
          "Scroll-spy table of contents that uses IntersectionObserver to track which section is in view and highlights it with an animated sliding bar. Supports three depth levels for indentation. Click-to-scroll built in.",
        file: "components/motion/page-nav.tsx",
        tags: ["navigation", "layout"],
        keywords: [
          "table of contents react",
          "scroll spy react",
          "page navigation react",
          "docs sidebar react",
          "active section tracker react",
        ],
      },
      {
        slug: "text-scramble",
        name: "Text Scramble",
        group: "Text",
        description:
          "Characters scramble through random symbols before resolving to the target string — left-to-right reveal with configurable charset, speed, and delay. Supports mount and hover triggers.",
        file: "components/motion/text-scramble.tsx",
        badge: "new",
        launchedAt: "2026-07-12",
        tags: ["text", "display", "animation"],
        keywords: [
          "text scramble react",
          "character scramble animation",
          "glitch text react",
          "typewriter scramble",
          "matrix text effect react",
        ],
      },
      {
        slug: "stagger-list",
        name: "Stagger List",
        group: "Animation",
        description:
          "Renders any list of items with a configurable staggered entrance animation. Items slide in from any direction with eased motion, delay, and per-item stagger.",
        file: "components/motion/stagger-list.tsx",
        badge: "new",
        launchedAt: "2026-07-12",
        tags: ["animation", "display", "list"],
        keywords: [
          "stagger animation react",
          "list animation react",
          "staggered entrance react",
          "sequential animation react",
          "framer motion stagger",
        ],
      },
      {
        slug: "progress",
        name: "Progress",
        group: "Status",
        description:
          "Animated progress bar with spring fill, five status variants (default, success, warning, error, info), four sizes, indeterminate mode, and a StackedProgress multi-segment variant with legend.",
        file: "components/motion/progress.tsx",
        tags: ["display", "feedback", "status"],
        keywords: [
          "react progress bar",
          "animated progress react",
          "progress indicator",
          "loading bar react",
          "stacked progress react",
        ],
      },
      {
        slug: "textarea",
        name: "Textarea",
        group: "Form",
        description:
          "Auto-resizing textarea with spring error-shake, success/error state icons, floating label, hint text, and min/max row bounds. Same classNames API as the motion Input.",
        file: "components/motion/textarea.tsx",
        tags: ["form", "input", "text"],
        keywords: [
          "react textarea",
          "auto resize textarea react",
          "animated textarea",
          "textarea validation react",
          "growing textarea react",
        ],
      },
      {
        slug: "skeleton",
        name: "Skeleton",
        group: "Status",
        description:
          "Shimmer loading placeholder with rect, circle, and multi-line text variants, plus SkeletonCard and SkeletonTable composites. Reduced-motion falls back to opacity pulse.",
        file: "components/motion/skeleton.tsx",
        tags: ["display", "feedback", "status"],
        keywords: [
          "react skeleton",
          "skeleton loader react",
          "shimmer effect react",
          "loading placeholder react",
          "content placeholder react",
        ],
      },
      {
        slug: "avatar",
        name: "Avatar",
        group: "Avatar",
        description:
          "Image with animated fallback (initials or icon), six sizes, four status dot indicators, and an AvatarGroup stacked with spring entrance and overflow counter.",
        file: "components/motion/avatar.tsx",
        tags: ["display", "avatar", "media"],
        keywords: [
          "react avatar",
          "avatar component react",
          "avatar group react",
          "user avatar react",
          "avatar with status react",
        ],
      },
      {
        slug: "combobox",
        name: "Combobox",
        group: "Form",
        description:
          "Searchable select with spring dropdown, layout-animated filtered list, selected checkmark, description rows, icon support, clear button, and an empty state.",
        file: "components/motion/combobox.tsx",
        tags: ["form", "input", "dropdown"],
        keywords: [
          "react combobox",
          "searchable select react",
          "animated select react",
          "autocomplete react",
          "react command select",
        ],
      },
      {
        slug: "text-morph",
        name: "Text Morph",
        group: "Text",
        description:
          "Morphs between strings character-by-character via layoutId — shared characters physically glide to their new positions, removed ones fade out, new ones fade in.",
        file: "components/motion/text-morph.tsx",
        tags: ["text", "display", "animation"],
        keywords: [
          "text morph react",
          "character morph animation",
          "text transition react",
          "animated text swap",
          "letter morph animation",
        ],
      },
      {
        slug: "morphing-text",
        name: "Morphing Text",
        group: "Text",
        description:
          "Auto-cycles through a list of words with each character blurring in from below and out upward with a staggered delay — a melting-and-reforming effect for hero headings.",
        file: "components/motion/morphing-text.tsx",
        tags: ["text", "display", "animation"],
        keywords: [
          "rotating text react",
          "word cycling animation",
          "hero text animation",
          "morphing headline react",
          "text blur effect",
        ],
      },
      {
        slug: "magic-card",
        name: "Magic Card",
        group: "Card",
        description:
          "Card with a spring-following radial gradient spotlight that tracks the cursor. The surface stays flat while a light source moves behind it.",
        file: "components/motion/magic-card.tsx",
        tags: ["interaction", "hover", "card"],
        keywords: [
          "magic card react",
          "cursor spotlight card",
          "hover glow card",
          "radial gradient hover",
          "interactive card react",
        ],
      },
      {
        slug: "border-beam",
        name: "Border Beam",
        group: "Visual",
        description:
          "A sweeping gradient comet that travels clockwise around the border of its container. Drop it inside any positioned element to add a dynamic border highlight.",
        file: "components/motion/border-beam.tsx",
        tags: ["visual", "display", "card"],
        keywords: [
          "border beam react",
          "animated border react",
          "gradient border animation",
          "glowing border react",
          "conic gradient border",
        ],
      },
      {
        slug: "orbiting-circles",
        name: "Orbiting Circles",
        group: "Animation",
        description:
          "Elements orbit a center point at configurable radii, speeds, and phase offsets. Multiple items stay upright throughout via counter-rotation.",
        file: "components/motion/orbiting-circles.tsx",
        badge: "new",
        launchedAt: "2026-06-20",
        tags: ["visual", "display", "animation"],
        keywords: [
          "orbiting circles react",
          "orbit animation react",
          "rotating icons react",
          "tech stack showcase animation",
          "circular orbit react",
        ],
      },
      {
        slug: "confetti",
        name: "Confetti",
        group: "Animation",
        description:
          "Canvas particle burst (circles, squares, ribbons) fired from any screen position. Exposes a fireConfetti() function and a ConfettiButton convenience wrapper. Respects prefers-reduced-motion.",
        file: "components/motion/confetti.tsx",
        badge: "new",
        launchedAt: "2026-06-22",
        tags: ["interaction", "feedback", "display"],
        keywords: [
          "confetti react",
          "celebration animation react",
          "particle burst react",
          "confetti button react",
          "success animation react",
        ],
      },
      {
        slug: "animated-beam",
        name: "Animated Beam",
        group: "Visual",
        description:
          "SVG beam that connects two DOM elements with an animated traveling spot of light along a static dim track. Supports bezier curvature, reverse direction, and multiple beams.",
        file: "components/motion/animated-beam.tsx",
        badge: "new",
        launchedAt: "2026-06-25",
        tags: ["visual", "display", "data"],
        keywords: [
          "animated beam react",
          "svg beam animation",
          "connection line animation react",
          "flow diagram react",
          "node connection animation",
        ],
      },
      {
        slug: "flickering-grid",
        name: "Flickering Grid",
        group: "Background",
        description:
          "Canvas grid where each cell independently and randomly updates its opacity, creating a living breathing background texture. Lightweight and customizable.",
        file: "components/motion/flickering-grid.tsx",
        badge: "new",
        launchedAt: "2026-06-27",
        tags: ["visual", "display", "background"],
        keywords: [
          "flickering grid react",
          "canvas grid background animation",
          "animated grid background react",
          "dot grid animation react",
          "pixel grid react",
        ],
      },
      {
        slug: "wheel-picker",
        name: "Wheel Picker",
        group: "Form",
        description:
          "iOS-style 3D cylinder picker with physics-based flick, touch drag, mouse drag, trackpad wheel, and keyboard navigation. Controlled and uncontrolled. Reduced-motion safe.",
        file: "components/motion/wheel-picker.tsx",
        badge: "new",
        launchedAt: "2026-07-09",
        tags: ["form", "input", "mobile", "interaction"],
        keywords: [
          "ios wheel picker react",
          "drum picker react",
          "cylinder picker",
          "date picker wheel react",
          "scroll picker react",
        ],
      },
      {
        slug: "globe",
        name: "Globe",
        group: "Visual",
        description:
          "Canvas-rendered rotating sphere with a fibonacci-distributed dot lattice, depth-cued opacity, and animated great-circle arcs. Zero dependencies beyond the canvas API.",
        file: "components/motion/globe.tsx",
        badge: "new",
        launchedAt: "2026-07-12",
        tags: ["visual", "display", "background", "marketing"],
        keywords: [
          "globe animation react",
          "3d globe react",
          "interactive globe react",
          "world map animation",
          "dot globe react",
        ],
      },
      {
        slug: "spotlight",
        name: "Spotlight",
        group: "Card",
        description:
          "SpotlightCard wraps any content and tracks the cursor with a spring-animated radial gradient glow. Spotlight is a static SVG variant for full-bleed hero sections.",
        file: "components/motion/spotlight.tsx",
        badge: "new",
        launchedAt: "2026-07-12",
        tags: ["visual", "hover", "card", "marketing"],
        keywords: [
          "spotlight effect react",
          "cursor spotlight card react",
          "mouse tracking glow react",
          "radial gradient hover react",
          "card spotlight react",
        ],
      },
      {
        slug: "typewriter",
        name: "Typewriter",
        group: "Text",
        description:
          "Types a word character-by-character, pauses, deletes, and cycles through an array of strings. Blinking cursor rendered with motion/react. Configurable speed and pause duration.",
        file: "components/motion/typewriter.tsx",
        badge: "new",
        launchedAt: "2026-07-12",
        tags: ["text", "animation", "display"],
        keywords: [
          "typewriter effect react",
          "typing animation react",
          "text cycle animation react",
          "hero text animation react",
          "delete type loop react",
        ],
      },
      {
        slug: "avatar-circles",
        name: "Avatar Circles",
        group: "Avatar",
        description:
          "Stacked overlapping avatar ring with image or fallback initials, configurable max count, and an animated +N overflow badge. Three sizes.",
        file: "components/motion/avatar-circles.tsx",
        badge: "new",
        launchedAt: "2026-07-12",
        tags: ["display", "avatar", "social", "marketing"],
        keywords: [
          "avatar stack react",
          "avatar circles react",
          "stacked avatars react",
          "user pile react",
          "social proof avatars react",
        ],
      },
      {
        slug: "badge-group",
        name: "Badge Group",
        group: "Badge",
        description: "Semantic pill badges in six variants (default, success, warning, error, info, secondary) with optional icon slot. No motion.",
        file: "components/static/badge-group.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["display", "feedback", "status"],
      },
      {
        slug: "callout",
        name: "Callout",
        group: "Display",
        description: "Contextual callout with a left accent border in five variants: info, success, warning, error, and tip. No motion.",
        file: "components/static/callout.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["display", "feedback"],
      },
      {
        slug: "kbd",
        name: "Keyboard Shortcut",
        group: "Display",
        description: "Keyboard key pill with a bevel shadow, plus a KbdShortcut wrapper for multi-key combos like ⌘K. No motion.",
        file: "components/static/kbd.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["display", "text"],
      },
      {
        slug: "empty-state",
        name: "Empty State",
        group: "Display",
        description: "Empty state card with dashed border, optional icon, title, description, and CTA action slot. No motion.",
        file: "components/static/empty-state.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["display", "feedback", "layout"],
      },
      {
        slug: "alert-banner",
        name: "Alert Banner",
        group: "Display",
        description: "Inline alert in four variants (info, success, warning, error) with an optional dismiss button. Static — no motion.",
        file: "components/static/alert-banner.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["display", "feedback", "notification"],
      },
      {
        slug: "segmented-control",
        name: "Segmented Control",
        group: "Form",
        description: "iOS-style segmented picker with a spring-animated selection pill. Supports icons, disabled options, sm/md sizes, and controlled/uncontrolled usage.",
        file: "components/motion/segmented-control.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["form", "input", "interaction", "toggle"],
      },
      {
        slug: "flip-card",
        name: "Flip Card",
        group: "Card",
        description: "3D CSS perspective flip card with composable front and back slots. Supports hover and click triggers with a spring rotation.",
        file: "components/motion/flip-card.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["interaction", "hover", "card", "display"],
      },
      {
        slug: "stepper",
        name: "Stepper",
        group: "Navigation",
        description: "Multi-step progress indicator with spring-animated active marker, animated check on completion, and a progress connector line. Works horizontally or vertically.",
        file: "components/motion/stepper.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["navigation", "layout", "feedback"],
      },
      {
        slug: "counter-ring",
        name: "Counter Ring",
        group: "Data",
        description: "Circular SVG progress ring with a spring count-up number that triggers on viewport entry. Configurable color, size, stroke, and suffix.",
        file: "components/motion/counter-ring.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["display", "data", "counter", "animation"],
      },
      {
        slug: "drag-to-confirm",
        name: "Drag to Confirm",
        group: "Interaction",
        description: "Drag the handle to the end to confirm an action. Springs back if not completed; shows a success state when done. Tap confirmed state to reset.",
        file: "components/motion/drag-to-confirm.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["interaction", "drag", "form", "mobile"],
      },
    ],
  },
  {
    slug: "blocks",
    name: "Patterns",
    description: "Composed, product-ready widgets built from Kinetic motion primitives.",
    components: [
      {
        slug: "pricing-card",
        name: "Pricing Card",
        group: "Marketing",
        description: "Plain pricing card with a feature checklist and CTA. No motion.",
        file: "components/static/pricing-card.tsx",
        badge: "new",
        launchedAt: "2026-07-14",
        tags: ["marketing", "display"],
      },
      {
        slug: "feature-grid",
        name: "Feature Grid",
        group: "Marketing",
        description: "Plain responsive grid of icon, title and description tiles. No motion.",
        file: "components/static/feature-grid.tsx",
        badge: "new",
        launchedAt: "2026-07-14",
        tags: ["marketing", "layout", "display"],
      },
      {
        slug: "swap",
        name: "Multi-chain Swap",
        group: "Finance",
        description: "Cross-chain swap widget with chain + token selectors, morphing views, animated flip and quote.",
        file: "components/motion/swap.tsx",
        tags: ["data", "form"],
      },
      {
        slug: "dynamic-island",
        name: "Dynamic Island",
        group: "Notification",
        description: "iOS-style island pill that morphs between live activity views with bouncy shell resize and blur crossfades.",
        file: "components/motion/dynamic-island.tsx",
        tags: ["overlay", "mobile", "notification"],
      },
      {
        slug: "command-palette",
        name: "Command Palette",
        group: "Navigation",
        description: "⌘K palette with fuzzy filter, spring-animated active row and glass surface.",
        file: "components/motion/command-palette.tsx",
        tags: ["navigation", "overlay"],
      },
      {
        slug: "expandable-action-bar",
        name: "Expandable Action Bar",
        group: "Navigation",
        description: "Compact icon actions that expand into labeled controls on hover or focus with shared layout motion.",
        file: "components/motion/expandable-action-bar.tsx",
        tags: ["navigation", "interaction", "layout"],
      },
      {
        slug: "overflow-actions",
        name: "Overflow Actions",
        group: "Navigation",
        description: "Connected pill rail for primary actions that springs open to reveal extra controls.",
        file: "components/motion/overflow-actions.tsx",
        tags: ["navigation", "interaction"],
      },
      {
        slug: "expandable-tabs",
        name: "Expandable Tabs",
        group: "Navigation",
        description: "Icon tab bar where the active tab expands to a labelled pill, with a panel above that morphs height and slides content direction-aware on switch.",
        file: "components/motion/expandable-tabs.tsx",
        tags: ["navigation", "mobile", "layout"],
      },
      {
        slug: "swipeable-list",
        name: "Swipeable List",
        group: "Mobile",
        description: "Mobile-style list rows that swipe left or right to reveal contextual action buttons.",
        file: "components/motion/swipeable-list.tsx",
        tags: ["mobile", "interaction", "drag"],
      },
      {
        slug: "file-upload",
        name: "File Upload",
        group: "Form",
        description: "Drag-and-drop upload queue with progress rows, retry/remove actions and reduced-motion-safe state changes.",
        file: "components/motion/file-upload.tsx",
        tags: ["form", "input", "drag"],
      },
      {
        slug: "prediction-market",
        name: "Prediction Market",
        group: "Finance",
        description: "Prediction market trade ticket with buy/sell modes, outcome prices, rolling amount entry, quick add chips and trade states.",
        file: "components/motion/prediction-market.tsx",
        tags: ["data", "form"],
      },
      {
        slug: "knockout-bracket",
        name: "Knockout Bracket",
        group: "Data",
        description: "Google-style tournament bracket that pages one round at a time, with spring-animated card reflow, CSS bracket connectors, country flag chips and shootout scores.",
        file: "components/motion/knockout-bracket.tsx",
        badge: "new",
        launchedAt: "2026-07-12",
        tags: ["data", "display"],
        keywords: [
          "tournament bracket react",
          "knockout bracket component",
          "bracket animation react",
          "sports bracket ui",
          "framer motion bracket",
        ],
      },
      {
        slug: "wallet-card",
        name: "Wallet Card",
        group: "Finance",
        description: "Wallet overview card with an account switcher and search that morph open from their triggers, a cascading balance with a live change pill and privacy toggle, copy-address, and Send / Deposit / Swap / Buy actions.",
        file: "components/motion/wallet-card/index.tsx",
        badge: "new",
        launchedAt: "2026-07-01",
        tags: ["data", "display"],
        keywords: [
          "wallet card react",
          "web3 wallet component",
          "crypto balance component",
          "account switcher react",
          "chain switcher react",
        ],
      },
      {
        slug: "otp-input",
        name: "OTP Input",
        group: "Form",
        description: "One-time-code input with a gliding focus ring, digits that roll in per slot, error shake and a success check draw.",
        file: "components/motion/otp-input.tsx",
        tags: ["form", "input", "text"],
      },
      {
        slug: "bloom-menu",
        name: "Bloom Menu",
        group: "Navigation",
        description: "A button that morphs open into a menu and blooms iris-out from the center, the grid revealing in every direction with radially staggered items.",
        file: "components/motion/bloom-menu.tsx",
        badge: "new",
        launchedAt: "2026-07-03",
        tags: ["navigation", "overlay", "interaction"],
      },
      {
        slug: "feedback-widget",
        name: "Feedback Widget",
        group: "Form",
        description: "Corner trigger that morphs open into a feedback popup with message entry and animated sending, success and retry states.",
        file: "components/motion/feedback-widget.tsx",
        badge: "new",
        launchedAt: "2026-07-05",
        tags: ["form", "overlay", "feedback"],
        keywords: [
          "react feedback widget",
          "feedback popover react",
          "in-app feedback component",
          "feedback form animation",
          "react feedback button",
        ],
      },
      {
        slug: "not-found",
        name: "404 / Not Found",
        group: "Display",
        description: "Animated 404 pages in five styles: glitch scramble, magnetic digits, cursor spotlight, a fanning card stack and a typed terminal.",
        file: "components/motion/not-found/index.tsx",
        tags: ["display"],
        extraFiles: [
          "components/motion/not-found/shared.tsx",
          "components/motion/not-found/glitch.tsx",
          "components/motion/not-found/magnetic.tsx",
          "components/motion/not-found/spotlight.tsx",
          "components/motion/not-found/stacked.tsx",
          "components/motion/not-found/terminal.tsx",
        ],
        examples: [
          {
            slug: "glitch",
            name: "Glitch",
            description:
              "Digits scramble through random glyphs before resolving, with a chromatic split on hover.",
            installSlug: "not-found-glitch",
            file: "components/motion/not-found/glitch.tsx",
            previewKey: "blocks/not-found-glitch",
            previewFile: "components/previews/blocks/not-found-glitch.preview.tsx",
          },
          {
            slug: "magnetic",
            name: "Magnetic",
            description:
              "Each digit is cursor-attracted via the Magnetic wrapper and springs back on leave.",
            installSlug: "not-found-magnetic",
            file: "components/motion/not-found/magnetic.tsx",
            previewKey: "blocks/not-found-magnetic",
            previewFile: "components/previews/blocks/not-found-magnetic.preview.tsx",
          },
          {
            slug: "spotlight",
            name: "Spotlight",
            description:
              "A dark panel where a cursor-tracked spotlight reveals the bright code from a dim base.",
            installSlug: "not-found-spotlight",
            file: "components/motion/not-found/spotlight.tsx",
            previewKey: "blocks/not-found-spotlight",
            previewFile: "components/previews/blocks/not-found-spotlight.preview.tsx",
          },
          {
            slug: "stacked",
            name: "Stacked",
            description:
              "A code card over a hidden stack that fans out with a spring on hover.",
            installSlug: "not-found-stacked",
            file: "components/motion/not-found/stacked.tsx",
            previewKey: "blocks/not-found-stacked",
            previewFile: "components/previews/blocks/not-found-stacked.preview.tsx",
          },
          {
            slug: "terminal",
            name: "Terminal",
            description:
              "A terminal window that types a failed cd command and a 404 status, with a blinking caret.",
            installSlug: "not-found-terminal",
            file: "components/motion/not-found/terminal.tsx",
            previewKey: "blocks/not-found-terminal",
            previewFile: "components/previews/blocks/not-found-terminal.preview.tsx",
          },
        ],
      },
      {
        slug: "pro-card",
        name: "Pro Card",
        group: "Marketing",
        badge: "new",
        launchedAt: "2026-07-11",
        description:
          "An upgrade / plan upsell card with an animated rainbow gradient border, badge, title, feature list, price display, and a RainbowCta button. Drop it in a sidebar or any narrow column.",
        file: "components/motion/pro-card.tsx",
        tags: ["display", "marketing"],
        keywords: [
          "upgrade card react",
          "pro plan card react",
          "pricing card react",
          "upsell card react",
          "subscription card react",
        ],
      },
      {
        slug: "availability-scheduler",
        name: "Availability Scheduler",
        group: "Form",
        badge: "new",
        launchedAt: "2026-07-11",
        description:
          "Weekly availability picker with per-day time slots, animated add/remove ranges, a copy-to-days morph popover, quick presets (Weekdays, Every day, Weekends, Clear), per-day hours display, and a visual weekly overview bar chart.",
        file: "components/motion/availability-scheduler/index.tsx",
        extraFiles: [
          "components/motion/availability-scheduler/day-row.tsx",
          "components/motion/availability-scheduler/time-select.tsx",
          "components/motion/availability-scheduler/copy-menu.tsx",
          "components/motion/availability-scheduler/icon-button.tsx",
          "components/motion/availability-scheduler/types.ts",
        ],
        tags: ["form", "input", "data"],
        keywords: [
          "availability scheduler react",
          "weekly schedule picker",
          "time slot picker react",
          "working hours component",
          "schedule form react",
        ],
      },
      {
        slug: "hero-video-dialog",
        name: "Hero Video Dialog",
        group: "Media",
        description:
          "Thumbnail with an animated play button that opens a fullscreen video dialog. Supports YouTube / Vimeo embed URLs or direct video files. Six configurable entry animations.",
        file: "components/motion/hero-video-dialog.tsx",
        badge: "new",
        launchedAt: "2026-07-06",
        tags: ["media", "overlay", "display"],
        keywords: [
          "hero video react",
          "video dialog react",
          "video lightbox react",
          "play button overlay react",
          "video modal react",
        ],
      },
      {
        slug: "login-form",
        name: "Login Form",
        group: "Auth",
        description: "Polished sign-in card with email/password fields, show-password toggle, error shake, loading state, and success state. Spring-animated throughout.",
        file: "components/motion/login-form.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["form", "input", "interaction"],
      },
      {
        slug: "notification-center",
        name: "Notification Center",
        group: "Notification",
        description: "Notification list with read/unread states, unread count badge, per-item dismiss, and mark-all-read. Items animate in and slide out on dismiss.",
        file: "components/motion/notification-center.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["notification", "display", "feedback"],
      },
      {
        slug: "user-profile-card",
        name: "User Profile Card",
        group: "Social",
        description: "Rich profile card with banner gradient, avatar, bio, location and website meta links, a follow button, and an animated stat row.",
        file: "components/motion/user-profile-card.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["display", "marketing", "social", "layout"],
      },
      {
        slug: "stats-row",
        name: "Stats Row",
        group: "Data",
        description: "Horizontal grid of KPI stat tiles with staggered entrance animation. Each tile shows a label, value, and optional up/down trend delta.",
        file: "components/motion/stats-row.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["data", "display", "layout", "marketing"],
      },
      {
        slug: "activity-feed",
        name: "Activity Feed",
        group: "Social",
        description: "Timestamped activity timeline with a vertical connector line and staggered entrance. Shows actor, action, target, and relative timestamp per row.",
        file: "components/motion/activity-feed.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["display", "data", "social"],
      },
      {
        slug: "bento-grid",
        name: "Bento Grid",
        group: "Layout",
        description:
          "CSS-grid bento layout with staggered card entrance, subtle scale-up hover, a metric tile, and an inline bar-chart tile — no charting library required.",
        file: "components/motion/bento-grid.tsx",
        badge: "new",
        launchedAt: "2026-07-12",
        tags: ["layout", "display", "marketing"],
        keywords: [
          "bento grid react",
          "bento box layout react",
          "dashboard grid react",
          "feature grid react",
          "animated grid react",
        ],
      },
    ],
  },
  {
    slug: "ai",
    name: "AI",
    description: "Production-ready UI primitives for chat interfaces, streaming responses, and AI agent workflows.",
    components: [
      {
        slug: "agent-input",
        name: "Agent Input",
        group: "Input",
        description: "Auto-resizing chat input with send / stop states, suggestion chips, and staged file attachments — wires directly into any AI SDK.",
        file: "components/ai/agent-input.tsx",
        badge: "new",
        launchedAt: "2026-07-04",
        tags: ["form", "input", "interaction"],
        keywords: [
          "ai chat input",
          "agent input bar",
          "chat input react",
          "llm chat input",
          "ai message input",
        ],
      },
      {
        slug: "chat-bubble",
        name: "Chat Bubble",
        group: "Chat",
        description: "Animated user and assistant message bubbles with a spring entry, typing indicator, and a composable MessageList for full conversation threads.",
        file: "components/ai/chat-bubble.tsx",
        badge: "new",
        launchedAt: "2026-07-04",
        tags: ["display", "feedback", "text"],
        keywords: [
          "chat bubble react",
          "ai message bubble",
          "chat message component",
          "llm chat ui",
          "assistant message react",
        ],
      },
      {
        slug: "streaming-text",
        name: "Streaming Text",
        group: "Text",
        description: "Character-by-character text reveal that tracks append-only target strings — simulates live token streaming. Includes a blinking cursor and a word-level TokenStream variant.",
        file: "components/ai/streaming-text.tsx",
        badge: "new",
        launchedAt: "2026-07-04",
        tags: ["display", "text", "animation"],
        keywords: [
          "streaming text react",
          "typewriter effect react",
          "ai text streaming",
          "character reveal react",
          "llm streaming response",
        ],
      },
      {
        slug: "tool-card",
        name: "Tool Card",
        group: "Display",
        description: "Collapsible card for AI tool invocations — shows the tool name, status (running / done / error) with spring-animated icon transitions, and an expandable input / output body.",
        file: "components/ai/tool-card.tsx",
        badge: "new",
        launchedAt: "2026-07-04",
        tags: ["display", "data", "feedback"],
        keywords: [
          "ai tool card react",
          "agent tool invocation",
          "llm tool use ui",
          "tool call react",
          "ai agent ui component",
        ],
      },
      {
        slug: "suggestion-chips",
        name: "Suggestion Chips",
        group: "Input",
        description: "Horizontally scrollable prompt suggestion chips with staggered spring entrance and scale hover. Pass an onSelect callback to wire into your AI input.",
        file: "components/ai/suggestion-chips.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["input", "interaction", "display"],
      },
      {
        slug: "model-picker",
        name: "Model Picker",
        group: "Input",
        description: "Dropdown for selecting an AI model with provider label, capability badge, and speed indicator. Spring enter/exit and outside-click dismiss.",
        file: "components/ai/model-picker.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["input", "form", "interaction"],
      },
      {
        slug: "thinking-indicator",
        name: "Thinking Indicator",
        group: "Feedback",
        description: "Animated AI thinking state in three variants: bouncing dots, indeterminate bar, and a radial pulse ring. Two sizes.",
        file: "components/ai/thinking-indicator.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["feedback", "animation", "display"],
      },
      {
        slug: "prompt-history",
        name: "Prompt History",
        group: "Display",
        description: "Collapsible list of previous prompts with spring reveal, configurable max visible, and an onSelect callback for reuse.",
        file: "components/ai/prompt-history.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["display", "data", "interaction"],
      },
      {
        slug: "token-counter",
        name: "Token Counter",
        group: "Display",
        description: "Live token or character counter with an animated spring fill bar. Color shifts from primary to amber to red as usage approaches the limit.",
        file: "components/ai/token-counter.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["display", "feedback", "data"],
      },
    ],
  },
  {
    slug: "templates",
    name: "Templates",
    description: "Full-section layout templates — hero, pricing, features, testimonials, and CTA — for rapid page assembly.",
    components: [
      {
        slug: "hero-section",
        name: "Hero Section",
        group: "Marketing",
        description: "Full-width hero section with eyebrow badge, headline, subheadline, CTA button slots, optional media slot, and staggered entrance animation. Center or left aligned.",
        file: "components/templates/hero-section.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["marketing", "layout", "display"],
      },
      {
        slug: "pricing-section",
        name: "Pricing Section",
        group: "Marketing",
        description: "3-column pricing section with per-plan feature lists, highlighted plan ring, popular badge, and staggered card entrance.",
        file: "components/templates/pricing-section.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["marketing", "display", "layout"],
      },
      {
        slug: "features-section",
        name: "Features Section",
        group: "Marketing",
        description: "Marketing feature grid with icon tiles, eyebrow, headline, subheadline, and staggered entrance. 2–4 column layouts.",
        file: "components/templates/features-section.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["marketing", "layout", "display"],
      },
      {
        slug: "testimonials-section",
        name: "Testimonials Section",
        group: "Marketing",
        description: "3-column testimonial card grid with star ratings, quote, author avatar, and staggered entrance animation.",
        file: "components/templates/testimonials-section.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["marketing", "display", "social"],
      },
      {
        slug: "cta-section",
        name: "CTA Section",
        group: "Marketing",
        description: "Full-width call-to-action section with two variants: a bordered card and a gradient fill. Slots for headline, subheadline, and action buttons.",
        file: "components/templates/cta-section.tsx",
        badge: "new",
        launchedAt: "2026-07-15",
        tags: ["marketing", "display", "layout"],
      },
    ],
  },
];

export function findCategory(slug: string) {
  return registry.find((c) => c.slug === slug);
}

export function findComponent(categorySlug: string, slug: string) {
  return findCategory(categorySlug)?.components.find((c) => c.slug === slug);
}

export function allComponents() {
  return registry.flatMap((c) =>
    c.components.map((comp) => ({ ...comp, category: c }))
  );
}

/** Top-level components and total installable targets (counting variants). */
export const COMPONENT_COUNT = registry.reduce(
  (n, c) => n + c.components.length,
  0,
);

export const INSTALLABLE_COUNT = registry.reduce(
  (n, c) =>
    n +
    c.components.reduce((m, comp) => {
      const variants = (comp.examples ?? []).filter((e) => e.installSlug).length;
      return m + (variants || 1);
    }, 0),
  0,
);
