/**
 * Canonical, frozen tag sets per category slug.
 * Import this in both server and client components.
 * Never add new tags without updating this list.
 */
export const CATEGORY_TAG_SETS: Record<string, string[]> = {
  motion: [
    "animation",
    "avatar",
    "background",
    "card",
    "counter",
    "data",
    "disclosure",
    "display",
    "drag",
    "dropdown",
    "feedback",
    "form",
    "hover",
    "input",
    "interaction",
    "layout",
    "list",
    "marketing",
    "media",
    "mobile",
    "navigation",
    "notification",
    "overlay",
    "scroll",
    "social",
    "status",
    "text",
    "toggle",
    "visual",
  ],
  blocks: [
    "data",
    "display",
    "drag",
    "feedback",
    "form",
    "input",
    "interaction",
    "layout",
    "marketing",
    "media",
    "mobile",
    "navigation",
    "notification",
    "overlay",
    "text",
  ],
  ai: [
    "animation",
    "data",
    "display",
    "feedback",
    "form",
    "input",
    "interaction",
    "text",
  ],
};
